version: "3"

services:
  svelte:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "REMSTROY_PROJECT"
    restart: always
    command:
      "npm run start"


  nginx:
    image: nginx:1.13
    container_name: "REMSTROY_NGINX"
    ports:
      - "4185:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - svelte
